/**
 * Every style in the member app.
 *
 * Moved out of `App.tsx` because it was 2,156 of that file's 8,039 lines —
 * a quarter of the file, scrolled past constantly, and the single biggest
 * reason reading a component meant paging through unrelated CSS.
 *
 * It is deliberately one object rather than one file per feature. Splitting
 * it further only helps once the components are split too, and doing both at
 * once would make the diff impossible to review against a working app. This
 * is the move that costs nothing and can be verified by a typecheck.
 *
 * Colours come from `./tokens`; nothing here should contain a hex literal
 * that is not a one-off shade with a comment explaining why it is not a
 * token. The minimum font size is 11 — see `MIN_FONT_SIZE` and the contrast
 * note in `./tokens`.
 */

import { StyleSheet } from "react-native";

import { C } from "./tokens";

export const s = StyleSheet.create({
  app: { flex: 1, backgroundColor: C.paper },
  scroll: { flex: 1 },
  content: { paddingHorizontal: 20, paddingTop: 22 },
  loading: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.paper,
    padding: 28,
    gap: 14,
  },
  loadingText: { color: C.soft, fontSize: 15 },
  topBar: {
    height: 56,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: C.paper,
  },
  wordmark: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  topLogo: { width: 36, height: 36, borderRadius: 11 },
  topBrand: {
    color: C.greenDeep,
    fontSize: 15,
    fontWeight: "800",
    letterSpacing: 0.1,
  },
  topBrandSub: {
    color: C.faint,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.1,
    marginTop: 1,
  },
  topActions: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  topAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: C.greenTint,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "transparent",
  },
  topAvatarActive: { borderColor: C.green },
  topAvatarText: { color: C.greenDeep, fontSize: 11, fontWeight: "800" },
  saving: { color: C.green, fontSize: 11 },
  savingQueued: { color: C.calm, fontSize: 11 },

  /* The record. Deliberately plain — this is the screen most likely to be read
     as a report card, so there is no colour that could mean "bad". */
  historyDay: { gap: 2 },
  historyDate: { color: C.ink, fontSize: 15, fontWeight: "700" },
  historyCount: { color: C.green, fontSize: 12, fontWeight: "700" },
  historyQuiet: { color: C.faint, fontSize: 13, marginTop: 6 },
  historyLine: {
    flexDirection: "row",
    gap: 10,
    marginTop: 10,
    alignItems: "flex-start",
  },
  historyDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    marginTop: 6,
    backgroundColor: C.green,
  },
  historyDotFood: { backgroundColor: C.marigold },
  historyDotPulse: { backgroundColor: C.calm },
  historyDotWater: { backgroundColor: "#8FBDB0" },
  historyItem: { color: C.ink, fontSize: 14, lineHeight: 20 },
  historyMeta: { color: C.faint, fontSize: 12, lineHeight: 17, marginTop: 1 },
  minutesOther: {
    color: C.greenDeep,
    fontSize: 13,
    fontWeight: "600",
    marginTop: 12,
    textAlign: "center",
  },
  minutesCustomRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 10,
  },
  minutesCustomUnit: { color: C.soft, fontSize: 14, fontWeight: "600" },

  /* The circle: what was captured, and help spelling a city. */
  areaCaptured: {
    color: C.soft,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 8,
  },
  cityList: {
    borderRadius: 13,
    borderWidth: 1,
    borderColor: C.line,
    overflow: "hidden",
    marginTop: 6,
  },
  cityRow: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    paddingVertical: 11,
    paddingHorizontal: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: C.line,
    backgroundColor: C.card,
  },
  cityName: { color: C.ink, fontSize: 14, fontWeight: "600" },
  cityRegion: { color: C.faint, fontSize: 12 },

  /* Offering a human coach, without pretending one is assigned. */
  upsell: {
    marginTop: 18,
    borderColor: "#DDC994",
    backgroundColor: C.marigoldTint,
  },
  upsellKicker: {
    color: C.marigoldInk,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.6,
    marginLeft: 8,
  },
  upsellTitle: {
    color: C.ink,
    fontSize: 17,
    fontWeight: "700",
    marginTop: 9,
  },
  upsellCopy: { color: C.soft, fontSize: 13, lineHeight: 19, marginTop: 5 },
  upsellButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 46,
    marginTop: 13,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: "#DDC994",
    backgroundColor: C.card,
  },
  upsellButtonText: { color: C.greenDeep, fontSize: 14, fontWeight: "700" },

  /* The Coach tab. Vera is labelled, never dressed up as a person. */
  coachHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    marginBottom: 16,
  },
  coachAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.greenTint,
    borderWidth: 1,
    borderColor: C.line,
  },
  coachName: { color: C.ink, fontSize: 21, fontWeight: "700" },
  coachRole: { color: C.soft, fontSize: 13, marginTop: 1 },
  coachIntro: { color: C.soft, fontSize: 14, lineHeight: 21 },
  humanCoachBubble: { borderLeftWidth: 3, borderLeftColor: C.marigold },
  messageFromHuman: { color: C.marigold },
  thinkingText: { color: C.soft, fontSize: 13, marginLeft: 8 },
  openerWrap: { gap: 8, marginTop: 4, marginBottom: 4 },
  opener: {
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.card,
  },
  openerText: { color: C.greenDeep, fontSize: 14, fontWeight: "600" },
  sendDisabled: { opacity: 0.4 },
  learnToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    minHeight: 62,
    marginBottom: 12,
    paddingHorizontal: 16,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.card,
  },

  /* Awards — one sideways row, with the description inside the same card. */
  awardsCard: {
    paddingHorizontal: 0,
    paddingTop: 15,
    paddingBottom: 0,
    overflow: "hidden",
  },
  awardStrip: { flexDirection: "row", gap: 6, paddingHorizontal: 13 },
  awardItem: { width: 74, alignItems: "center" },
  awardBadge: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 1.5,
    borderColor: C.line,
    backgroundColor: "#F7F8F4",
    alignItems: "center",
    justifyContent: "center",
  },
  awardBadgeEarned: {
    borderColor: "#DDC994",
    backgroundColor: C.marigoldTint,
  },
  awardBadgeActive: { borderWidth: 2.5, borderColor: C.marigold },
  awardLabel: {
    color: C.faint,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "600",
    textAlign: "center",
    marginTop: 7,
  },
  awardLabelEarned: { color: C.soft },
  awardLabelActive: { color: C.ink, fontWeight: "700" },
  awardDetail: {
    marginTop: 15,
    paddingHorizontal: 17,
    paddingVertical: 14,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: C.line,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    backgroundColor: "#F7F8F4",
  },
  awardDetailEarned: { backgroundColor: C.marigoldTint },
  awardDetailTitle: {
    color: C.ink,
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 4,
  },
  awardDetailCopy: { color: C.soft, fontSize: 13, lineHeight: 19 },
  awardDetailState: {
    color: C.faint,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.4,
    textTransform: "uppercase",
    marginTop: 8,
  },
  awardDetailStateEarned: { color: C.marigold },
  actionCardInline: {
    backgroundColor: "transparent",
    borderWidth: 0,
    shadowOpacity: 0,
    elevation: 0,
    marginTop: 0,
    marginBottom: 6,
    paddingHorizontal: 0,
    paddingTop: 0,
  },
  rowInline: { flexDirection: "row", alignItems: "center", gap: 8 },
  circleTodayCard: { gap: 10 },
  circleTodayRow: { flexDirection: "row", gap: 14, marginTop: 2 },
  circleTodayPerson: { alignItems: "center", width: 56 },
  circleTodayAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: C.greenTint,
    alignItems: "center",
    justifyContent: "center",
  },
  circleTodayMore: { backgroundColor: C.line },
  circleTodayInitial: { color: C.greenDeep, fontSize: 15, fontWeight: "800" },
  circleTodayName: { color: C.ink, fontSize: 11, marginTop: 5 },
  circleTodayDays: { color: C.faint, fontSize: 10, marginTop: 1 },
  calendarToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minHeight: 46,
    marginTop: 14,
    marginBottom: 12,
    paddingHorizontal: 14,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.card,
  },
  calendarToggleText: {
    color: C.green,
    flex: 1,
    fontSize: 14,
    fontWeight: "700",
  },

  /* Today at a glance — five rows instead of ten stacked cards. */
  glanceCard: { paddingVertical: 6 },
  domainRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    minHeight: 62,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: C.line,
  },
  /** First row in a glance card: the divider has nothing to divide. */
  domainRowFirst: { borderTopWidth: 0 },
  domainRowPressed: { opacity: 0.6 },
  domainRowIcon: {
    width: 34,
    height: 34,
    borderRadius: 11,
    backgroundColor: C.greenTint,
    alignItems: "center",
    justifyContent: "center",
  },
  domainRowIconDone: { backgroundColor: C.green },
  domainRowLabel: {
    color: C.faint,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.9,
  },
  domainRowTitle: {
    color: C.ink,
    fontSize: 15,
    fontWeight: "600",
    marginTop: 2,
  },
  domainRowTitleDone: { color: C.soft },
  domainRowDetail: { color: C.faint, fontSize: 12, marginTop: 2 },
  domainRowCount: {
    color: C.green,
    fontSize: 13,
    fontWeight: "800",
    fontVariant: ["tabular-nums"],
  },

  /* The movement session screen. */
  backRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    minHeight: 44,
    marginBottom: 4,
  },
  backRowText: { color: C.green, fontSize: 15, fontWeight: "700" },
  /* Quiet on purpose: finishing early is a valid choice, not a failure. */
  endSession: {
    alignSelf: "center",
    minHeight: 44,
    justifyContent: "center",
    paddingHorizontal: 18,
    marginTop: 6,
    marginBottom: 8,
  },
  endSessionText: { color: C.soft, fontSize: 13, fontWeight: "700" },
  sessionProgress: { flexDirection: "row", gap: 5, marginTop: 16 },
  sessionPip: {
    flex: 1,
    height: 4,
    borderRadius: 2,
    backgroundColor: C.line,
  },
  sessionPipDone: { backgroundColor: C.green },

  /* Consistency grid — 28 days, four rows of seven. A quiet day is lighter,
     never marked. There is deliberately no red in this component. */
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 3,
    width: 7 * 14,
    marginVertical: 12,
  },
  gridCell: { borderRadius: 2.5, backgroundColor: C.line },
  gridCell1: { backgroundColor: "#CFE0DA" },
  gridCell2: { backgroundColor: "#8FBDB0" },
  gridCell3: { backgroundColor: C.green },

  personCard: { gap: 4 },
  personName: { color: C.ink, fontSize: 16, fontWeight: "700" },
  personBio: { color: C.soft, fontSize: 13, lineHeight: 19, marginTop: 2 },
  personMeta: { color: C.faint, fontSize: 12, marginTop: 2 },
  nudgeButton: {
    minHeight: 42,
    marginTop: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    alignItems: "center",
    justifyContent: "center",
  },
  nudgeButtonText: { color: C.green, fontSize: 13, fontWeight: "700" },
  nudgeCard: { backgroundColor: C.marigoldTint },
  nudgeLine: { color: C.ink, fontSize: 14, lineHeight: 21, marginTop: 6 },
  nudgeFrom: { fontWeight: "700" },
  bioInput: { minHeight: 78, paddingTop: 13, textAlignVertical: "top" },

  /* Readiness screen. Plain, unhurried, nothing red. */
  readinessBlock: {
    marginBottom: 6,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: C.line,
  },
  readinessPrompt: { color: C.ink, fontSize: 15, lineHeight: 22 },
  readinessHint: { color: C.faint, fontSize: 12, lineHeight: 17, marginTop: 5 },
  readinessRow: { flexDirection: "row", gap: 8, marginTop: 11 },
  readinessChoice: {
    flex: 1,
    minHeight: 46,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    alignItems: "center",
    justifyContent: "center",
  },
  readinessOutcome: {
    marginTop: 16,
    padding: 14,
    borderRadius: 13,
    backgroundColor: C.greenTint,
  },
  readinessOutcomeTitle: {
    color: C.greenDeep,
    fontSize: 15,
    fontWeight: "700",
  },
  readinessOutcomeBody: {
    color: C.greenDeep,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 6,
  },

  /* Water — a row of glasses that fill. No target line, no shortfall. */
  waterRow: {
    flexDirection: "row",
    gap: 7,
    marginTop: 14,
    flexWrap: "wrap",
  },
  waterGlass: {
    width: 30,
    height: 38,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: C.line,
    backgroundColor: "#F7F8F4",
  },
  waterGlassFilled: { backgroundColor: "#BFDCE4", borderColor: C.calm },
  waterExtra: { color: C.calm, fontSize: 11, marginTop: 8, fontWeight: "700" },
  waterAdd: {
    minHeight: 44,
    marginTop: 12,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: C.line,
    alignItems: "center",
    justifyContent: "center",
  },
  waterAddText: { color: C.green, fontSize: 14, fontWeight: "700" },

  /* Habits. */
  habitRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 12,
  },
  habitTap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    minHeight: 44,
  },
  habitBox: {
    width: 24,
    height: 24,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: C.line,
    alignItems: "center",
    justifyContent: "center",
  },
  habitBoxDone: { backgroundColor: C.green, borderColor: C.green },
  habitLabel: { color: C.ink, flex: 1, fontSize: 15 },
  habitLabelDone: { color: C.soft },
  habitRemove: { color: C.faint, fontSize: 22, paddingHorizontal: 6 },
  habitAddRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    marginTop: 12,
  },
  habitAddButton: {
    minWidth: 60,
    minHeight: 52,
    paddingHorizontal: 14,
    borderRadius: 13,
    backgroundColor: C.greenTint,
    alignItems: "center",
    justifyContent: "center",
  },
  habitAddButtonText: { color: C.greenDeep, fontSize: 14, fontWeight: "700" },
  habitSuggestions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
  },
  habitChip: {
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderRadius: 11,
    backgroundColor: "#F7F8F4",
    borderWidth: 1,
    borderColor: C.line,
  },
  habitChipText: { color: C.green, fontSize: 12, fontWeight: "600" },

  /* Circle. */
  circleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 12,
    paddingVertical: 9,
    paddingHorizontal: 11,
    borderRadius: 12,
    backgroundColor: "#F7F8F4",
  },
  circleRowMe: { backgroundColor: C.greenTint },
  circleRank: {
    color: C.faint,
    fontSize: 13,
    fontWeight: "800",
    minWidth: 16,
    textAlign: "center",
  },
  circleName: { color: C.ink, fontSize: 15, fontWeight: "700" },
  circleMeta: { color: C.soft, fontSize: 11, lineHeight: 16, marginTop: 3 },
  requestRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 12,
  },
  requestName: { color: C.ink, fontSize: 15, fontWeight: "700" },
  requestMeta: { color: C.faint, fontSize: 11, marginTop: 2 },
  requestAccept: {
    minHeight: 44,
    paddingHorizontal: 15,
    borderRadius: 12,
    backgroundColor: C.green,
    alignItems: "center",
    justifyContent: "center",
  },
  requestAcceptText: { color: "#fff", fontSize: 13, fontWeight: "700" },
  requestDecline: {
    minHeight: 44,
    paddingHorizontal: 13,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    alignItems: "center",
    justifyContent: "center",
  },
  requestDeclineText: { color: C.soft, fontSize: 13, fontWeight: "600" },
  settingLabel: {
    color: C.ink,
    fontSize: 14,
    fontWeight: "700",
    marginTop: 14,
  },
  settingCopy: { color: C.faint, fontSize: 11, lineHeight: 16, marginTop: 4 },
  errorTitle: {
    color: C.ink,
    fontSize: 17,
    fontWeight: "700",
    textAlign: "center",
  },

  /* Offline notice — informative, never a failure state. */
  offlineBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginHorizontal: 20,
    marginTop: 4,
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderRadius: 11,
    backgroundColor: "#E8EFF1",
  },
  offlineText: { color: C.calm, flex: 1, fontSize: 11, lineHeight: 16 },

  /* Unread coach replies. */
  tabBadge: {
    position: "absolute",
    top: -2,
    right: 2,
    minWidth: 16,
    height: 16,
    paddingHorizontal: 4,
    borderRadius: 8,
    backgroundColor: C.green,
    alignItems: "center",
    justifyContent: "center",
  },
  tabBadgeText: { color: "#fff", fontSize: 11, fontWeight: "800" },

  /* Reminder time control. */
  reminderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginTop: 14,
  },
  reminderStep: {
    width: 44,
    height: 44,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: C.line,
    alignItems: "center",
    justifyContent: "center",
  },
  reminderTime: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    minHeight: 44,
    borderRadius: 13,
    backgroundColor: C.greenTint,
  },
  reminderTimeText: { color: C.greenDeep, fontSize: 15, fontWeight: "700" },

  /* Export and deletion. */
  dataButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    minHeight: 46,
    marginTop: 12,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: C.line,
  },
  dataButtonText: { color: C.green, fontSize: 14, fontWeight: "700" },
  deleteLinkText: { color: C.soft },
  deleteBox: {
    marginTop: 14,
    padding: 14,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: "#F7F8F4",
    gap: 10,
  },
  deleteTitle: { color: C.ink, fontSize: 14, fontWeight: "700" },
  deleteActions: { flexDirection: "row", gap: 10 },
  deleteConfirmButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#A34336",
  },
  deleteConfirmText: { color: "#fff", fontSize: 14, fontWeight: "700" },

  /* What a meal estimate was read from. */
  /* ---------------------------------------------------------------- */
  /* An estimate she has not agreed to yet                              */
  /*                                                                    */
  /* Deliberately reads as a question rather than as a saved record:    */
  /* an outlined card rather than a filled one, and the confirm button  */
  /* says what will happen rather than "OK".                            */
  /* ---------------------------------------------------------------- */
  proposalCard: {
    marginTop: 14,
    padding: 15,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.green,
    backgroundColor: C.greenTint,
    gap: 4,
  },
  proposalTitle: { color: C.ink, fontSize: 15, fontWeight: "800" },
  proposalCopy: { color: C.soft, fontSize: 12, lineHeight: 17 },
  /* Which reading she is looking at: the photo, or her own words. */
  sourceRow: { flexDirection: "row", gap: 8, marginTop: 12 },
  sourceChip: {
    flex: 1,
    minHeight: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.card,
    alignItems: "center",
    justifyContent: "center",
  },
  sourceChipActive: { borderColor: C.greenDeep, backgroundColor: C.greenDeep },
  sourceChipText: { color: C.soft, fontSize: 12, fontWeight: "700" },
  sourceChipTextActive: { color: "white", fontWeight: "800" },
  proposalItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: C.line,
  },
  proposalItemName: { color: C.ink, fontSize: 14, fontWeight: "700" },
  proposalItemMacros: {
    color: C.faint,
    fontSize: 12,
    marginTop: 2,
    fontVariant: ["tabular-nums"],
  },
  portionRow: { flexDirection: "row", alignItems: "center", gap: 4 },
  /* 44pt targets: these are tapped repeatedly while correcting a plate. */
  portionButton: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: C.line,
    alignItems: "center",
    justifyContent: "center",
  },
  portionButtonText: { color: C.greenDeep, fontSize: 19, fontWeight: "800" },
  portionValue: {
    minWidth: 30,
    textAlign: "center",
    color: C.ink,
    fontSize: 14,
    fontWeight: "800",
    fontVariant: ["tabular-nums"],
  },
  portionRemove: {
    width: 36,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  proposalTotal: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: C.green,
  },
  proposalTotalLabel: { color: C.ink, fontSize: 13, fontWeight: "800" },
  proposalTotalValue: {
    color: C.greenDeep,
    fontSize: 14,
    fontWeight: "800",
    fontVariant: ["tabular-nums"],
  },
  proposalActions: { flexDirection: "row", gap: 9, marginTop: 14 },
  proposalBasis: { color: C.faint, fontSize: 12, marginTop: 10 },

  loginPage: { flex: 1, backgroundColor: C.paper },
  authScroll: { flexGrow: 1, paddingBottom: 28 },
  authHero: {
    paddingHorizontal: 28,
    paddingTop: 58,
    paddingBottom: 38,
    borderBottomLeftRadius: 34,
    borderBottomRightRadius: 34,
  },
  brandIcon: { width: 64, height: 64, borderRadius: 18, marginBottom: 18 },
  brand: {
    fontSize: 12,
    color: "#D9C28D",
    fontWeight: "800",
    letterSpacing: 1.8,
  },
  loginTitle: {
    fontSize: 34,
    lineHeight: 40,
    color: "#FFFFFF",
    fontWeight: "700",
    marginTop: 20,
  },
  loginCopy: {
    color: "#D6E1DD",
    fontSize: 15,
    lineHeight: 23,
    marginTop: 9,
    maxWidth: 420,
  },
  authCard: {
    marginHorizontal: 20,
    marginTop: -14,
    padding: 20,
    borderRadius: 24,
    backgroundColor: C.card,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.line,
  },
  inputLabel: {
    color: C.ink,
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 7,
    marginTop: 12,
    letterSpacing: 0.2,
  },
  optional: { color: C.faint, fontWeight: "500" },
  input: {
    backgroundColor: "#F7F8F4",
    borderColor: C.line,
    borderWidth: 1,
    borderRadius: 13,
    color: C.ink,
    fontSize: 16,
    minHeight: 52,
    paddingHorizontal: 15,
  },
  /* The field and its reveal button share one bordered box. */
  passwordRow: { position: "relative", justifyContent: "center" },
  passwordInput: { paddingRight: 52 },
  passwordReveal: {
    position: "absolute",
    right: 4,
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  fieldHint: { color: C.faint, fontSize: 11, marginTop: 5 },
  error: { color: "#A34336", fontSize: 13, lineHeight: 19, marginTop: 12 },
  notice: { color: C.green, fontSize: 13, lineHeight: 19, marginTop: 12 },
  privacyNote: {
    color: C.faint,
    fontSize: 11,
    lineHeight: 17,
    marginTop: 18,
    marginHorizontal: 28,
    textAlign: "center",
  },
  primaryButton: {
    minHeight: 52,
    borderRadius: 14,
    backgroundColor: C.greenDeep,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    marginTop: 20,
  },
  primaryButtonText: { color: "white", fontSize: 15, fontWeight: "700" },
  secondaryButton: {
    minHeight: 50,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.line,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 12,
    paddingHorizontal: 14,
  },
  secondaryButtonText: { color: C.ink, fontWeight: "600", fontSize: 14 },
  textButton: {
    color: C.green,
    textAlign: "center",
    fontSize: 13,
    fontWeight: "700",
    paddingTop: 15,
  },
  authDivider: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 18,
  },
  dividerLine: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: C.line,
    flex: 1,
  },
  dividerText: { color: C.faint, fontSize: 10, fontWeight: "700" },
  pressed: { opacity: 0.82 },
  eyebrow: {
    color: C.green,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.1,
    marginBottom: 8,
  },
  hero: { color: C.ink, fontSize: 30, lineHeight: 36, fontWeight: "700" },
  heroCopy: {
    color: C.soft,
    fontSize: 15,
    lineHeight: 22,
    marginTop: 5,
    marginBottom: 20,
  },
  card: {
    backgroundColor: C.card,
    borderRadius: 20,
    padding: 17,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.line,
    marginBottom: 12,
  },
  compactCard: { paddingVertical: 14 },
  cardTitle: { color: C.ink, fontSize: 15, fontWeight: "700" },
  cardCopy: { color: C.soft, fontSize: 13, lineHeight: 19, marginTop: 6 },

  /* ---------------------------------------------------------------- */
  /* The Log hub                                                       */
  /*                                                                   */
  /* Four capture cards in a two-by-two grid rather than a list: they  */
  /* are peers, and a list would imply an order she should follow.     */
  /* ---------------------------------------------------------------- */
  captureGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 9,
    marginTop: 18,
  },
  captureCard: {
    /* Two per row, accounting for the gap. */
    width: "48%",
    flexGrow: 1,
    minHeight: 116,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.card,
    padding: 14,
    justifyContent: "flex-start",
  },
  captureIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: C.greenTint,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 9,
  },
  captureLabel: { color: C.ink, fontSize: 15, fontWeight: "800" },
  captureDetail: {
    color: C.faint,
    fontSize: 12,
    lineHeight: 16,
    marginTop: 3,
  },
  /* Quiet on purpose: it marks what she has given, never what she owes. */
  captureDone: {
    color: C.green,
    fontSize: 11,
    fontWeight: "700",
    marginTop: 7,
  },
  quickCaptureCard: { marginTop: 18 },
  quickModeRow: { flexDirection: "row", gap: 8, marginTop: 12 },
  quickModeChip: {
    flex: 1,
    minHeight: 46,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: C.line,
    alignItems: "center",
    justifyContent: "center",
  },
  quickModeChipActive: {
    backgroundColor: C.greenDeep,
    borderColor: C.greenDeep,
  },
  quickModeText: { color: C.soft, fontSize: 13, fontWeight: "700" },
  quickModeTextActive: { color: "white", fontWeight: "800" },
  /* The "· today" after a feed row's title. */
  feedWhen: { color: C.faint, fontSize: 12, fontWeight: "600" },
  removeLink: { color: C.marigoldInk, fontSize: 12, fontWeight: "700" },
  rowBetween: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  saved: { color: C.green, fontSize: 11, fontWeight: "600" },
  sectionHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "baseline",
    marginTop: 12,
    marginBottom: 10,
  },
  sectionTitle: {
    color: C.ink,
    fontSize: 17,
    fontWeight: "700",
    marginTop: 16,
    marginBottom: 10,
  },
  sectionHeadTitle: { color: C.ink, fontSize: 17, fontWeight: "700" },
  sectionMeta: { color: C.faint, fontSize: 12 },
  empty: { color: C.soft, fontSize: 14, lineHeight: 20, textAlign: "center" },
  planChange: {
    backgroundColor: C.greenTint,
    borderRadius: 17,
    padding: 15,
    marginBottom: 12,
  },
  planLabel: { color: C.green, fontSize: 12, fontWeight: "700" },
  planCopy: { color: C.soft, fontSize: 13, lineHeight: 19, marginTop: 5 },
  moodRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 16,
  },
  mood: { alignItems: "center", flex: 1 },
  moodCircle: {
    width: 45,
    height: 45,
    borderRadius: 23,
    backgroundColor: C.paper,
    alignItems: "center",
    justifyContent: "center",
  },
  moodCircleActive: { backgroundColor: C.greenTint },
  moodGlyph: { color: C.faint, fontSize: 21 },
  moodGlyphActive: { color: C.green, fontWeight: "700" },
  moodLabel: { color: C.faint, fontSize: 11, marginTop: 6 },
  moodLabelActive: { color: C.ink, fontWeight: "600" },
  pulseSummary: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: C.line,
    color: C.soft,
    fontSize: 12,
    marginTop: 14,
    paddingTop: 12,
  },
  pulseDetailsButton: {
    minHeight: 44,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: C.line,
    marginTop: 12,
    paddingTop: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  pulseDetailsText: { color: C.greenDeep, fontSize: 12, fontWeight: "800" },
  pulseDetails: { paddingTop: 2 },
  sleepRow: { flexDirection: "row", gap: 8 },
  sleepChoice: {
    flex: 1,
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: C.paper,
    borderWidth: 1,
    borderColor: C.line,
    alignItems: "center",
    justifyContent: "center",
  },
  sleepChoiceActive: { backgroundColor: C.greenDeep, borderColor: C.greenDeep },
  sleepChoiceValue: { color: C.soft, fontSize: 14, fontWeight: "800" },
  sleepChoiceValueActive: { color: "white" },
  sleepScaleLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 5,
  },
  sleepScaleLabel: { color: C.faint, fontSize: 9 },
  signalWrap: { flexDirection: "row", flexWrap: "wrap", gap: 7 },
  signalChip: {
    minHeight: 40,
    maxWidth: "100%",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.paper,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  signalChipActive: { backgroundColor: C.greenTint, borderColor: C.green },
  signalChipText: { color: C.soft, fontSize: 11, fontWeight: "600" },
  signalChipTextActive: { color: C.greenDeep, fontWeight: "800" },
  signalNote: { color: C.faint, fontSize: 10, lineHeight: 15, marginTop: 11 },
  flowLabel: {
    color: C.green,
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1,
    marginTop: 13,
    marginBottom: 9,
  },
  snapshotCard: { padding: 15 },
  snapshotIntro: { color: C.faint, fontSize: 10, marginTop: 3 },
  snapshotGrid: {
    flexDirection: "row",
    gap: 6,
    marginTop: 12,
  },
  snapshotTile: {
    flex: 1,
    minHeight: 74,
    borderRadius: 13,
    backgroundColor: C.paper,
    paddingVertical: 10,
    paddingHorizontal: 8,
  },
  snapshotTileAction: { borderWidth: 1, borderColor: C.greenTint },
  snapshotIcon: {
    width: 22,
    height: 22,
    borderRadius: 8,
    backgroundColor: C.greenTint,
    alignItems: "center",
    justifyContent: "center",
  },
  snapshotLabel: { color: C.faint, fontSize: 11, marginTop: 6 },
  /** A reading that is not from today, and must not read as if it were. */
  snapshotValueStale: { color: C.soft },
  snapshotDetailStale: { color: C.marigoldInk, fontWeight: "600" },
  snapshotValue: {
    color: C.ink,
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "800",
    marginTop: 2,
  },
  snapshotDetail: { color: C.soft, fontSize: 11, lineHeight: 13, marginTop: 2 },
  insightCard: {
    flexDirection: "row",
    gap: 12,
    borderRadius: 20,
    padding: 17,
    marginBottom: 12,
    backgroundColor: C.marigoldTint,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#DDC994",
  },
  insightIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: "#FFFFFF90",
    alignItems: "center",
    justifyContent: "center",
  },
  insightBody: { flex: 1 },
  insightLabel: {
    color: C.marigoldInk,
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.9,
  },
  insightTitle: { color: C.ink, fontSize: 16, fontWeight: "800", marginTop: 4 },
  insightCopy: { color: C.soft, fontSize: 12, lineHeight: 18, marginTop: 5 },
  insightEvidence: {
    color: C.faint,
    fontSize: 11,
    lineHeight: 14,
    marginTop: 8,
  },
  coachConnection: { padding: 18, marginTop: 2 },
  coachConnectionReview: { backgroundColor: "#F8EDE7", borderColor: "#DFC0B4" },
  coachConnectionTop: { flexDirection: "row", gap: 11, alignItems: "center" },
  coachMark: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: C.greenTint,
    alignItems: "center",
    justifyContent: "center",
  },
  coachConnectionKicker: {
    color: C.marigoldInk,
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.9,
  },
  coachConnectionTitle: {
    color: C.ink,
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "800",
    marginTop: 3,
  },
  coachConnectionCopy: {
    color: C.soft,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 13,
  },
  coachConnectionMeta: {
    color: C.faint,
    fontSize: 10,
    lineHeight: 15,
    marginTop: 8,
  },
  coachConnectionButton: {
    minHeight: 46,
    borderRadius: 13,
    backgroundColor: C.greenDeep,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    marginTop: 14,
  },
  coachConnectionButtonText: {
    color: "white",
    fontSize: 12,
    fontWeight: "800",
  },
  consistencyCard: { borderRadius: 22, padding: 18, marginBottom: 12 },
  consistencyLabel: {
    color: "#BDD5CF",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.2,
  },
  consistencyCount: { color: "#E8D39E", fontSize: 12, fontWeight: "800" },
  consistencyTitle: {
    color: "white",
    fontSize: 19,
    lineHeight: 25,
    fontWeight: "700",
    marginTop: 12,
  },
  consistencyTrack: {
    height: 7,
    borderRadius: 4,
    backgroundColor: "#FFFFFF28",
    overflow: "hidden",
    marginTop: 15,
  },
  consistencyFill: {
    height: "100%",
    borderRadius: 4,
    backgroundColor: "#D7B86F",
  },
  rhythmDots: { flexDirection: "row", gap: 7, marginTop: 10 },
  rhythmDot: {
    flex: 1,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#FFFFFF24",
  },
  rhythmDotDone: { backgroundColor: "#D7B86F" },
  challengeStrip: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#FFFFFF35",
    marginTop: 16,
    paddingTop: 13,
  },
  challengeKicker: { color: "#E8D39E", fontSize: 11, fontWeight: "800" },
  challengeCopy: {
    color: "#DCE9E5",
    fontSize: 12,
    lineHeight: 17,
    marginTop: 4,
  },
  shareWin: {
    alignSelf: "flex-start",
    marginTop: 13,
    borderRadius: 12,
    backgroundColor: "#FFFFFF14",
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  shareWinText: { color: "white", fontSize: 11, fontWeight: "700" },
  actionCard: { padding: 16 },
  actionTop: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  domainIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.greenTint,
  },
  domainLabel: {
    color: C.green,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.8,
    marginBottom: 3,
  },
  actionText: { flex: 1 },
  actionTitle: {
    color: C.ink,
    fontSize: 16,
    fontWeight: "700",
    lineHeight: 21,
  },
  actionOutcome: { color: C.soft, fontSize: 11, lineHeight: 15, marginTop: 2 },
  whyBlock: {
    backgroundColor: C.paper,
    borderRadius: 13,
    padding: 12,
    marginTop: 12,
  },
  whyLabel: {
    color: C.green,
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1,
  },
  actionWhy: { color: C.soft, fontSize: 13, lineHeight: 19, marginTop: 4 },
  recommendationEvidence: {
    color: C.faint,
    fontSize: 10,
    lineHeight: 15,
    marginTop: 6,
  },
  actionStatus: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 2,
    borderColor: C.line,
    alignItems: "center",
    justifyContent: "center",
  },
  actionStatusDone: { backgroundColor: C.green, borderColor: C.green },
  effortRow: { flexDirection: "row", gap: 7, marginTop: 15 },
  effort: {
    flex: 1,
    minHeight: 62,
    borderRadius: 12,
    backgroundColor: C.paper,
    padding: 8,
    justifyContent: "center",
  },
  effortActive: { backgroundColor: C.green },
  effortLabel: { color: C.ink, fontSize: 11, fontWeight: "700" },
  effortDetail: { color: C.faint, fontSize: 11, lineHeight: 12, marginTop: 3 },
  effortLabelActive: { color: "white" },
  exerciseBlock: {
    backgroundColor: C.greenTint,
    borderRadius: 16,
    marginTop: 14,
    padding: 12,
  },
  exerciseSets: { color: C.greenDeep, fontSize: 12, fontWeight: "800" },
  exerciseCue: {
    color: C.green,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
  },
  frameRow: { flexDirection: "row", gap: 5, marginTop: 12 },
  frame: {
    flex: 1,
    minHeight: 92,
    borderRadius: 10,
    backgroundColor: C.card,
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 3,
  },
  figureHead: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: C.greenDeep,
  },
  figureBody: {
    width: 3,
    height: 25,
    borderRadius: 2,
    backgroundColor: C.green,
    marginTop: 2,
  },
  figureBase: {
    width: 15,
    height: 3,
    borderRadius: 2,
    backgroundColor: C.marigold,
    marginTop: 2,
  },
  frameLabel: {
    color: C.soft,
    textAlign: "center",
    fontSize: 11,
    lineHeight: 10,
    marginTop: 6,
  },
  formCue: { color: C.soft, fontSize: 11, lineHeight: 16, marginTop: 10 },
  /** Three ways a day went, offered without ranking them. */
  skipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    // Centred. Without this the row defaults to flex-start and three pills
    // hug the left edge under a full-width three-column block above them,
    // which reads as a mistake rather than a choice.
    justifyContent: "center",
    gap: 8,
    marginTop: 12,
  },
  skipOption: {
    paddingVertical: 9,
    paddingHorizontal: 13,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.card,
  },
  skipOptionText: { color: C.greenDeep, fontSize: 13, fontWeight: "600" },
  notToday: {
    color: C.faint,
    fontSize: 12,
    textAlign: "center",
    paddingTop: 13,
    paddingBottom: 2,
  },
  listRow: { flexDirection: "row", gap: 10, marginTop: 13 },
  bullet: { color: C.green, fontSize: 15, fontWeight: "700" },
  listText: { flex: 1, color: C.ink, fontSize: 15, lineHeight: 21 },
  dotRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 18,
  },
  dayDot: { width: 14, height: 14, borderRadius: 7, backgroundColor: C.line },
  dayDotDone: { backgroundColor: C.green },
  metricRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 13,
  },
  metricDay: { color: C.soft, fontSize: 11, width: 48 },
  metricTrack: {
    flex: 1,
    height: 7,
    borderRadius: 4,
    backgroundColor: C.line,
    overflow: "hidden",
  },
  metricFill: { height: "100%", backgroundColor: C.green, borderRadius: 4 },
  metricValue: { width: 25, color: C.soft, fontSize: 11 },
  sleepMetricFill: { backgroundColor: C.calm },
  trendSummary: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 9,
    marginTop: 16,
    marginBottom: 2,
  },
  trendValue: { color: C.greenDeep, fontSize: 24, fontWeight: "800" },
  trendLabel: { flex: 1, color: C.soft, fontSize: 11, lineHeight: 16 },
  trendEvidence: {
    color: C.faint,
    fontSize: 11,
    lineHeight: 14,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: C.line,
    paddingTop: 10,
    marginTop: 13,
  },
  signalHistoryRow: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: C.line,
  },
  signalHistoryName: { flex: 1, color: C.ink, fontSize: 12, fontWeight: "600" },
  signalHistoryCount: { color: C.green, fontSize: 10, fontWeight: "800" },
  session: {
    backgroundColor: C.marigoldTint,
    borderRadius: 19,
    padding: 18,
    marginBottom: 8,
  },
  sessionLabel: {
    color: C.marigoldInk,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1,
  },
  sessionTitle: { color: C.ink, fontSize: 18, fontWeight: "700", marginTop: 7 },
  sessionMeta: { color: C.soft, fontSize: 13, marginTop: 3 },
  /* Reaching back through the conversation. */
  showEarlier: {
    alignSelf: "center",
    minHeight: 44,
    justifyContent: "center",
    paddingHorizontal: 16,
    marginBottom: 10,
  },
  showEarlierText: { color: C.green, fontSize: 13, fontWeight: "700" },
  messageBubble: {
    maxWidth: "88%",
    borderRadius: 18,
    padding: 14,
    marginBottom: 9,
  },
  coachBubble: { alignSelf: "flex-start", backgroundColor: C.marigoldTint },
  memberBubble: { alignSelf: "flex-end", backgroundColor: C.greenDeep },
  messageFrom: { color: C.green, fontSize: 11, fontWeight: "800" },
  messageFromCoach: { color: C.marigold },
  messageTime: { color: C.faint, fontSize: 9 },
  messageBody: { color: C.ink, fontSize: 14, lineHeight: 21, marginTop: 6 },
  memberMessageText: { color: "white" },
  composer: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 18,
    padding: 7,
    marginTop: 14,
  },
  composerInput: {
    flex: 1,
    color: C.ink,
    fontSize: 15,
    lineHeight: 20,
    minHeight: 40,
    maxHeight: 100,
    paddingHorizontal: 9,
    paddingVertical: 9,
  },
  sendButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: C.greenDeep,
    alignItems: "center",
    justifyContent: "center",
  },
  sendButtonText: { color: "white", fontSize: 22, fontWeight: "600" },
  responseNote: {
    color: C.faint,
    fontSize: 10,
    lineHeight: 15,
    textAlign: "center",
    marginTop: 8,
  },
  heroUnit: { fontSize: 15, color: C.soft, fontWeight: "500" },
  mealInput: {
    minHeight: 86,
    paddingTop: 13,
    textAlignVertical: "top",
    marginTop: 12,
  },
  captureRow: { flexDirection: "row", gap: 8, marginTop: 10 },
  photoButton: {
    flex: 1,
    minHeight: 48,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  photoButtonText: { color: C.green, fontSize: 13, fontWeight: "700" },
  estimateButton: { flex: 1.3, marginTop: 0, minHeight: 48 },
  mealPhoto: { width: "100%", height: 170, borderRadius: 14, marginTop: 12 },
  estimateNote: { color: C.faint, fontSize: 10, lineHeight: 15, marginTop: 10 },
  foodCard: { flexDirection: "row", gap: 12 },
  foodThumb: { width: 64, height: 64, borderRadius: 12 },
  foodText: { flex: 1 },
  calories: { color: C.green, fontSize: 12, fontWeight: "800" },
  macroText: { color: C.soft, fontSize: 11, marginTop: 5 },
  aiTag: {
    color: C.marigoldInk,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.7,
    marginTop: 8,
  },
  profileBadge: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: C.greenTint,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    marginBottom: 12,
  },
  profileInitials: { color: C.green, fontSize: 24, fontWeight: "700" },
  center: { textAlign: "center" },
  flex: { flex: 1, paddingRight: 14 },
  profileCopy: { color: C.soft, fontSize: 14, lineHeight: 21, marginTop: 9 },
  circleCard: { borderRadius: 22, padding: 18, marginBottom: 12 },
  circleKicker: {
    color: C.green,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.2,
  },
  circleTitle: {
    color: C.ink,
    fontSize: 20,
    lineHeight: 25,
    fontWeight: "700",
    marginTop: 8,
  },
  inviteCode: {
    backgroundColor: "#FFFFFF90",
    borderRadius: 13,
    padding: 12,
    marginTop: 14,
  },
  inviteCodeLabel: {
    color: C.faint,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
  },
  inviteCodeValue: {
    color: C.greenDeep,
    fontSize: 16,
    fontWeight: "800",
    letterSpacing: 0.8,
    marginTop: 3,
  },
  circleButton: {
    minHeight: 46,
    borderRadius: 13,
    backgroundColor: C.greenDeep,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  circleButtonText: { color: "white", fontSize: 13, fontWeight: "700" },
  policyLinks: { flexDirection: "row", gap: 22, marginTop: 15 },
  policyLink: {
    color: C.green,
    fontSize: 13,
    fontWeight: "700",
    textDecorationLine: "underline",
  },
  disclaimer: {
    color: C.faint,
    fontSize: 11,
    lineHeight: 17,
    textAlign: "center",
    marginTop: 20,
  },
  tabShell: {
    backgroundColor: C.card,
    paddingHorizontal: 8,
    paddingTop: 5,
    paddingBottom: 7,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: C.line,
  },
  tabBar: {
    minHeight: 62,
    backgroundColor: C.card,
    flexDirection: "row",
    paddingHorizontal: 3,
  },
  tab: {
    flex: 1,
    minHeight: 54,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
  },
  tabPressed: { backgroundColor: C.paper },
  tabIcon: {
    height: 28,
    minWidth: 38,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  tabIconActive: { backgroundColor: C.greenTint },
  tabLabel: {
    color: C.faint,
    // Was 9pt — the smallest text in the app, on its most permanent control.
    // 11 matches the platform convention (iOS 10–11, Material 12) and reads
    // without making the bar taller.
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.1,
  },
  tabLabelActive: { color: C.greenDeep, fontWeight: "800" },
  exerciseSequenceFrame: {
    width: "100%",
    height: 104,
    borderRadius: 13,
    marginTop: 12,
    overflow: "hidden",
    backgroundColor: "#F7F0E7",
  },
  exerciseSequence: { width: "100%", height: "100%" },
  exerciseSteps: { flexDirection: "row", gap: 4, marginTop: 8 },
  exerciseStep: { flex: 1, alignItems: "center" },
  exerciseStepNumber: {
    width: 17,
    height: 17,
    borderRadius: 9,
    backgroundColor: C.greenDeep,
    color: "white",
    textAlign: "center",
    textAlignVertical: "center",
    fontSize: 11,
    fontWeight: "800",
  },
  exerciseStepLabel: {
    color: C.soft,
    textAlign: "center",
    fontSize: 11,
    lineHeight: 10,
    marginTop: 4,
  },
  workoutLog: {
    marginTop: 14,
    padding: 14,
    borderRadius: 15,
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: "#C9D9D3",
  },
  logTitle: { color: C.ink, fontSize: 15, fontWeight: "800" },
  logLabel: {
    color: C.faint,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.8,
    marginTop: 14,
    marginBottom: 7,
  },
  ratingRow: { flexDirection: "row", gap: 7 },
  ratingButton: {
    flex: 1,
    height: 38,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.paper,
  },
  ratingButtonActive: { backgroundColor: C.greenDeep },
  ratingText: { color: C.soft, fontSize: 13, fontWeight: "700" },
  ratingTextActive: { color: "white" },
  painRow: { flexDirection: "row", gap: 8 },
  painChoice: {
    flex: 1,
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    alignItems: "center",
    justifyContent: "center",
  },
  painChoiceActive: { backgroundColor: C.greenTint, borderColor: C.green },
  painChoiceWarning: { backgroundColor: "#F8E4DF", borderColor: "#C86A59" },
  painChoiceText: { color: C.soft, fontSize: 12, fontWeight: "700" },
  painChoiceTextActive: { color: C.greenDeep },
  painChoiceWarningText: { color: "#943D32" },
  /* The three questions, shown only once she has said there was pain. */
  painDetail: {
    marginTop: 14,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: C.line,
  },
  painDetailGap: { marginTop: 16 },
  /* Full width, because it is a statement rather than one of a set. */
  painStopped: { alignSelf: "flex-start", marginTop: 14 },
  painWarning: { color: "#943D32", fontSize: 11, lineHeight: 16, marginTop: 9 },
  logButton: {
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: C.greenDeep,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 12,
  },
  logButtonText: { color: "white", fontSize: 13, fontWeight: "800" },
  onboardingProgress: { flexDirection: "row", gap: 6, marginBottom: 14 },
  onboardingProgressPart: {
    flex: 1,
    height: 4,
    borderRadius: 2,
    backgroundColor: C.line,
  },
  onboardingProgressActive: { backgroundColor: C.green },
  onboardingCard: { padding: 20 },
  onboardingTitle: {
    color: C.ink,
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "700",
  },
  onboardingCopy: { color: C.soft, fontSize: 14, lineHeight: 21, marginTop: 7 },
  optionStack: { gap: 9, marginTop: 18 },
  option: {
    minHeight: 52,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.line,
    paddingHorizontal: 15,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  optionActive: { backgroundColor: C.greenTint, borderColor: C.green },
  optionText: { color: C.soft, fontSize: 14, fontWeight: "600" },
  optionTextActive: { color: C.greenDeep, fontWeight: "800" },
  minutesRow: { flexDirection: "row", gap: 8, marginTop: 20 },
  minuteChoice: {
    flex: 1,
    height: 58,
    borderRadius: 14,
    backgroundColor: C.paper,
    alignItems: "center",
    justifyContent: "center",
  },
  minuteChoiceActive: { backgroundColor: C.greenDeep },
  minuteText: { color: C.ink, fontSize: 17, fontWeight: "800" },
  minuteTextActive: { color: "white" },
  minuteUnit: { fontSize: 11, fontWeight: "600" },
  /** An explicit "nothing to add", so a blank field cannot stand in for one. */
  nothingToAdd: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    marginTop: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.card,
  },
  nothingToAddOn: { borderColor: C.green, backgroundColor: C.greenTint },
  nothingToAddText: { flex: 1, color: C.ink, fontSize: 14, lineHeight: 19 },
  checkBox: {
    width: 21,
    height: 21,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: C.faint,
    alignItems: "center",
    justifyContent: "center",
  },
  checkBoxOn: { borderColor: C.green, backgroundColor: C.green },
  cautionInput: {
    minHeight: 94,
    textAlignVertical: "top",
    paddingTop: 13,
    marginTop: 17,
  },
  onboardingActions: { flexDirection: "row", gap: 9, marginTop: 22 },
  backButton: {
    minHeight: 48,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  backButtonText: { color: C.soft, fontSize: 13, fontWeight: "700" },
  continueButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 13,
    backgroundColor: C.greenDeep,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  continueButtonText: { color: "white", fontSize: 13, fontWeight: "800" },
  disabledButton: { opacity: 0.35 },
  articleCard: {
    borderRadius: 18,
    padding: 17,
    backgroundColor: C.card,
    marginBottom: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.line,
  },
  articleMeta: { flexDirection: "row", justifyContent: "space-between" },
  articleCategory: {
    color: C.marigoldInk,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.9,
  },
  articleMinutes: { color: C.faint, fontSize: 10 },
  articleTitle: { color: C.ink, fontSize: 17, fontWeight: "700", marginTop: 9 },
  articleSummary: { color: C.soft, fontSize: 13, lineHeight: 19, marginTop: 5 },
  articleOpen: {
    color: C.green,
    fontSize: 12,
    fontWeight: "800",
    marginTop: 12,
  },
  learningDetail: {
    borderRadius: 20,
    padding: 20,
    backgroundColor: C.card,
    marginTop: 16,
    marginBottom: 12,
  },
  learningBack: {
    color: C.green,
    fontSize: 13,
    fontWeight: "800",
    marginBottom: 20,
  },
  learningCategory: {
    color: C.marigoldInk,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.9,
  },
  learningTitle: {
    color: C.ink,
    fontSize: 25,
    lineHeight: 31,
    fontWeight: "700",
    marginTop: 9,
    marginBottom: 9,
  },
  learningParagraph: {
    color: C.soft,
    fontSize: 15,
    lineHeight: 24,
    marginTop: 11,
  },
  educationNote: {
    backgroundColor: C.paper,
    borderRadius: 12,
    padding: 12,
    marginTop: 18,
  },
  educationNoteText: { color: C.faint, fontSize: 10, lineHeight: 15 },
  reportCount: {
    minWidth: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: C.greenTint,
    color: C.greenDeep,
    textAlign: "center",
    textAlignVertical: "center",
    fontSize: 12,
    fontWeight: "800",
  },
  reportCategories: { flexDirection: "row", gap: 7, marginTop: 15 },
  reportCategory: {
    flex: 1,
    minHeight: 44,
    borderRadius: 11,
    backgroundColor: C.paper,
    alignItems: "center",
    justifyContent: "center",
  },
  reportCategoryActive: { backgroundColor: C.greenTint },
  reportCategoryText: { color: C.faint, fontSize: 11, fontWeight: "700" },
  reportCategoryTextActive: { color: C.greenDeep },
  uploadButton: {
    minHeight: 47,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: C.green,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 9,
  },
  uploadButtonText: { color: C.greenDeep, fontSize: 13, fontWeight: "800" },
  reportRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: C.line,
    paddingTop: 12,
    marginTop: 12,
  },
  reportFileIcon: {
    width: 35,
    height: 35,
    borderRadius: 10,
    backgroundColor: C.marigoldTint,
    alignItems: "center",
    justifyContent: "center",
  },
  reportFileText: { color: C.marigoldInk, fontSize: 11, fontWeight: "900" },
  reportText: { flex: 1 },
  reportName: { color: C.ink, fontSize: 12, fontWeight: "700" },
  reportMeta: { color: C.faint, fontSize: 11, marginTop: 3 },
  reportStatus: { color: C.green, fontSize: 11, fontWeight: "800" },
  reportPrivacy: {
    color: C.faint,
    fontSize: 11,
    lineHeight: 14,
    marginTop: 13,
  },
  dayMap: { paddingBottom: 15 },
  dayMapRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 5,
    marginTop: 15,
  },
  dayMapItem: { flex: 1, alignItems: "center" },
  dayMapIcon: {
    width: 38,
    height: 38,
    borderRadius: 13,
    backgroundColor: C.greenTint,
    alignItems: "center",
    justifyContent: "center",
  },
  dayMapIconDone: { backgroundColor: C.green },
  dayMapLabel: {
    color: C.soft,
    fontSize: 11,
    lineHeight: 10,
    textAlign: "center",
    marginTop: 6,
  },
  selectionCount: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 16,
  },
  selectionCountText: { color: C.greenDeep, fontSize: 11, fontWeight: "800" },
  selectionLimit: { color: C.marigoldInk, fontSize: 10, fontWeight: "700" },
  goalOptionText: { flex: 1, paddingVertical: 11 },
  /* A group of goals under one heading, so ten options read as three lists. */
  goalGroup: { marginTop: 20 },
  goalGroupLabel: {
    color: C.faint,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.7,
    textTransform: "uppercase",
  },
  /* The one line that says what a goal actually means for her plan. */
  goalDetail: { color: C.faint, fontSize: 12, lineHeight: 16, marginTop: 2 },
  /*
   * Her ranking, as a numbered badge rather than the words "Priority 2".
   *
   * The order she picks in decides which movement patterns lead the session,
   * so it is worth showing; it is not worth a line of prose per selected goal.
   */
  goalPriority: {
    width: 22,
    height: 22,
    borderRadius: 11,
    marginLeft: 10,
    backgroundColor: C.greenDeep,
    color: "white",
    fontSize: 11,
    fontWeight: "800",
    textAlign: "center",
    lineHeight: 22,
    overflow: "hidden",
  },
  emphasis: { color: C.ink, fontWeight: "800" },

  /* ---------------------------------------------------------------- */
  /* The optional detail questions, in onboarding and in About you     */
  /* ---------------------------------------------------------------- */
  /* Something the plan could not do, and the reason. */
  planNotice: {
    marginTop: 16,
    padding: 15,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.greenTint,
    gap: 6,
  },
  /* A held movement domain is a health message, not an update. */
  planNoticeSerious: {
    backgroundColor: C.marigoldTint,
    borderColor: C.marigold,
  },
  planNoticeHead: { flexDirection: "row", alignItems: "center", gap: 7 },
  planNoticeTitle: { color: C.ink, fontSize: 14, fontWeight: "800", flex: 1 },
  planNoticeBody: { color: C.soft, fontSize: 13, lineHeight: 19 },

  /* The event questions, set apart because they belong to the goal above. */
  eventBlock: {
    marginTop: 20,
    paddingTop: 18,
    borderTopWidth: 1,
    borderTopColor: C.line,
  },
  detailBlock: { marginTop: 24 },
  detailLabel: { color: C.ink, fontSize: 14, fontWeight: "800" },
  detailHint: { color: C.faint, fontSize: 12, lineHeight: 17, marginTop: 3 },
  /* Wrapping chips: the answers are short and there are a lot of them. */
  chipWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 12 },
  chip: {
    minHeight: 44,
    paddingHorizontal: 14,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: C.line,
    alignItems: "center",
    justifyContent: "center",
  },
  chipActive: { backgroundColor: C.greenTint, borderColor: C.green },
  chipText: { color: C.soft, fontSize: 13, fontWeight: "700" },
  chipTextActive: { color: C.greenDeep, fontWeight: "800" },
  /* A day chip is square-ish, because they sit seven in a row. */
  dayChip: { minWidth: 44, paddingHorizontal: 8 },
  detailInput: { minHeight: 84, paddingTop: 14, textAlignVertical: "top" },
  aboutSummary: {
    color: C.faint,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 6,
  },
  customGoalRow: { flexDirection: "row", gap: 8, marginTop: 12 },
  customGoalInput: { flex: 1 },
  addGoalButton: {
    width: 60,
    minHeight: 52,
    borderRadius: 13,
    backgroundColor: C.greenDeep,
    alignItems: "center",
    justifyContent: "center",
  },
  addGoalText: { color: "white", fontSize: 12, fontWeight: "800" },
  customGoalChip: {
    alignSelf: "flex-start",
    minHeight: 44,
    borderRadius: 18,
    backgroundColor: C.marigoldTint,
    justifyContent: "center",
    paddingHorizontal: 12,
    marginTop: 8,
  },
  customGoalChipText: { color: C.ink, fontSize: 10, fontWeight: "700" },
  consentStack: { marginTop: 17 },
  consentRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 13,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: C.line,
  },
  consentTitle: { color: C.ink, fontSize: 13, fontWeight: "700" },
  consentCopy: { color: C.soft, fontSize: 10, lineHeight: 15, marginTop: 3 },
  journeyHeroRow: { flexDirection: "row", justifyContent: "space-between" },
  journeyTrack: {
    height: 7,
    borderRadius: 4,
    backgroundColor: C.line,
    overflow: "hidden",
    marginTop: -7,
    marginBottom: 17,
  },
  journeyTrackFill: {
    height: "100%",
    borderRadius: 4,
    backgroundColor: C.marigold,
  },
  phaseGrid: { flexDirection: "row", gap: 7, marginBottom: 6 },
  phaseCard: {
    flex: 1,
    minHeight: 130,
    borderRadius: 16,
    backgroundColor: C.card,
    padding: 11,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.line,
  },
  phaseCardActive: { backgroundColor: C.greenDeep, borderColor: C.greenDeep },
  phaseName: { color: C.ink, fontSize: 11, fontWeight: "800" },
  phaseNameActive: { color: "white" },
  phaseWeeks: {
    color: C.marigoldInk,
    fontSize: 11,
    fontWeight: "800",
    marginTop: 3,
  },
  phasePromise: { color: C.faint, fontSize: 11, lineHeight: 13, marginTop: 9 },
  weekTimeline: { gap: 7, paddingBottom: 12, paddingRight: 10 },
  weekButton: {
    width: 51,
    minHeight: 58,
    borderRadius: 15,
    backgroundColor: C.card,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: C.line,
  },
  weekButtonPast: { backgroundColor: C.greenTint },
  weekButtonCurrent: { backgroundColor: C.greenDeep, borderColor: C.greenDeep },
  weekButtonSelected: { borderColor: C.marigold, borderWidth: 2 },
  weekNumber: { color: C.ink, fontSize: 15, fontWeight: "800" },
  weekNumberActive: { color: "white" },
  weekState: { color: C.faint, fontSize: 11, marginTop: 2 },
  weekDetail: { padding: 19 },
  weekDetailKicker: {
    color: C.green,
    fontSize: 11,
    lineHeight: 11,
    fontWeight: "900",
    letterSpacing: 0.9,
  },
  weekDetailTitle: {
    color: C.ink,
    fontSize: 22,
    fontWeight: "700",
    marginTop: 5,
  },
  weekDetailCount: { color: C.marigoldInk, fontSize: 10, fontWeight: "800" },
  weekDetailSection: {
    color: C.faint,
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.8,
    marginTop: 19,
  },
  moduleChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
    marginTop: 10,
  },
  moduleChip: {
    borderRadius: 14,
    backgroundColor: C.greenTint,
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  moduleChipText: {
    color: C.greenDeep,
    fontSize: 10,
    fontWeight: "700",
    textTransform: "capitalize",
  },
  weekWin: {
    flexDirection: "row",
    gap: 10,
    backgroundColor: C.marigoldTint,
    borderRadius: 14,
    padding: 13,
    marginTop: 17,
  },
  /** Shown when the week held nothing notable, which is most weeks. */
  weekQuiet: { color: C.soft, fontSize: 13, lineHeight: 19, marginTop: 14 },
  weekWinTitle: { color: C.ink, fontSize: 12, fontWeight: "800" },
  weekWinCopy: { color: C.soft, fontSize: 11, lineHeight: 16, marginTop: 3 },
  planReason: {
    backgroundColor: C.greenTint,
    borderRadius: 14,
    padding: 13,
    marginTop: 13,
  },
  calendarCard: { paddingHorizontal: 10 },
  calendarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 4,
    marginBottom: 8,
  },
  calendarArrow: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: C.paper,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarMonth: { color: C.ink, fontSize: 15, fontWeight: "800" },
  calendarGrid: { flexDirection: "row", flexWrap: "wrap" },
  weekday: {
    width: "14.285%",
    color: C.faint,
    fontSize: 11,
    fontWeight: "800",
    textAlign: "center",
    paddingBottom: 8,
  },
  calendarDay: {
    width: "14.285%",
    height: 53,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarDaySelected: { backgroundColor: C.greenDeep },
  calendarDayNumber: { color: C.ink, fontSize: 12, fontWeight: "700" },
  calendarDayNumberSelected: { color: "white" },
  calendarKcal: { color: C.faint, fontSize: 11, marginTop: 1 },
  proteinDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: C.marigoldTint,
    marginTop: 2,
  },
  proteinDotFull: { backgroundColor: C.marigold },
  calendarLegend: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 4,
    padding: 9,
  },
  legendDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: C.marigold,
  },
  legendText: { color: C.faint, fontSize: 11, lineHeight: 12 },
  mealChoiceRow: { flexDirection: "row", gap: 5, marginTop: 14 },
  mealChoice: {
    flex: 1,
    minHeight: 44,
    borderRadius: 10,
    backgroundColor: C.paper,
    alignItems: "center",
    justifyContent: "center",
  },
  mealChoiceActive: { backgroundColor: C.greenTint },
  mealChoiceText: { color: C.faint, fontSize: 11, fontWeight: "700" },
  mealChoiceTextActive: { color: C.greenDeep },
  foodMeal: {
    color: C.marigoldInk,
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.8,
    marginBottom: 3,
  },
  foodFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
  },
  memberTag: { color: C.green },
  editFoodButton: {
    minHeight: 36,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
  },
  removeFoodText: {
    color: C.soft,
    fontSize: 12,
    fontWeight: "700",
  },
  editFoodText: { color: C.greenDeep, fontSize: 10, fontWeight: "700" },
  inlineEditDescription: { minHeight: 45 },
  macroEditRow: { flexDirection: "row", gap: 5, marginTop: 9 },
  macroEdit: { flex: 1 },
  macroEditLabel: {
    color: C.faint,
    fontSize: 11,
    fontWeight: "800",
    marginBottom: 4,
  },
  macroEditInput: {
    minHeight: 40,
    borderRadius: 9,
    backgroundColor: C.paper,
    color: C.ink,
    fontSize: 12,
    textAlign: "center",
  },
  saveCorrectionButton: {
    minHeight: 44,
    borderRadius: 11,
    backgroundColor: C.greenDeep,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  saveCorrectionText: { color: "white", fontSize: 11, fontWeight: "800" },
  healthCard: { padding: 18 },
  healthHeader: { flexDirection: "row", alignItems: "center", gap: 11 },
  healthIcon: {
    width: 46,
    height: 46,
    borderRadius: 15,
    backgroundColor: C.greenTint,
    alignItems: "center",
    justifyContent: "center",
  },
  healthIconConnected: { backgroundColor: C.green },
  healthStatus: { color: C.faint, fontSize: 10, marginTop: 3 },
  healthMessage: {
    backgroundColor: C.marigoldTint,
    borderRadius: 12,
    padding: 11,
    marginTop: 12,
  },
  healthMessageText: { color: C.soft, fontSize: 10, lineHeight: 15 },
  permissionGrid: { gap: 7, marginTop: 14 },
  permissionItem: { borderRadius: 13, backgroundColor: C.paper, padding: 12 },
  permissionLabel: { color: C.ink, fontSize: 11, fontWeight: "700" },
  permissionState: { color: C.faint, fontSize: 11, fontWeight: "800" },
  permissionGranted: { color: C.green },
  healthValue: {
    color: C.greenDeep,
    fontSize: 18,
    fontWeight: "800",
    marginTop: 7,
  },
  healthSource: { color: C.faint, fontSize: 11, marginTop: 3 },
  healthButtons: { marginTop: 4 },
  healthPrimary: { flexDirection: "row", gap: 7 },
  manageHealthButton: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 5,
  },
  manageHealthText: { color: C.greenDeep, fontSize: 11, fontWeight: "800" },
  lastSync: { color: C.faint, textAlign: "center", fontSize: 11, marginTop: 4 },
  healthPrivacy: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: C.line,
    marginTop: 14,
    paddingTop: 12,
  },
  healthPrivacyText: { flex: 1, color: C.faint, fontSize: 11, lineHeight: 14 },
});
