/**
 * What counts as an acute signal, versus a permanent fact about her.
 *
 * A recommendation must never be generated by a model when something acute
 * just happened — pain on a logged movement, a symptom in a recent check-in.
 * Those get a fixed, deterministic "a person should look at this" response
 * instead, computed here, before any model is ever called.
 *
 * This used to also scan `member.goals` and `member.constraints` against the
 * same clinical-language pattern. Those are permanent profile fields, not
 * events — and "Support hormonal or life-stage wellbeing" is one of only
 * seven onboarding goal choices, aimed squarely at this app's stated
 * demographic. Picking it matched on the word "hormonal" alone and
 * permanently blocked every future AI recommendation for that member, since
 * nothing anywhere ever moves a recommendation's status away from
 * needs_coach_review. Confirmed against production data: the account that
 * had picked that goal was stuck on exactly this from its first
 * recommendation onward. A caution she wrote is not ignored by removing this
 * — it already drives the movement plan directly through the readiness
 * screen and eligibleExercises()'s avoidIf tagging, which is deterministic
 * and has a real, resolvable outcome, unlike this dead-end flag.
 */

import { randomUUID } from "node:crypto";
import type { MemberDoc } from "./persist";
import type { AiRecommendation } from "./types";

/**
 * Language a model's own generated text should never contain unreviewed.
 * Also used to gate the model's output in the caller — see guardRecommendation
 * in app/api/recommendations/generate/route.ts.
 */
export const HORMONE_OR_CLINICAL_LANGUAGE =
  /\b(body\s*signals?|symptoms?|pain(?:ful)?|injur(?:y|ed)|bleed(?:ing)?|hot\s*(?:flash|flush)(?:es)?|night\s*sweats?|dizz(?:y|iness)|faint(?:ing)?|palpitations?|cramps?|cramping|pregnan(?:t|cy)|hormon(?:e|al|es)?|progesterone|oestrogen|estrogen|testosterone|cortisol|thyroid|perimenopaus(?:e|al)?|menopaus(?:e|al)?|postmenopaus(?:e|al)?|menstrual|diagnos(?:e|ed|is|tic)|clinical|medications?|dosage|prescri(?:be|bed|ption)|blood\s*(?:test|work)|lab\s*(?:test|result)|disease|syndrome)\b/i;

type CompatibleWorkoutLog = {
  actionId?: string;
  workoutId?: string;
  pain?: boolean;
  painFlag?: boolean;
  coachReviewRequired?: boolean;
};

function workoutLogsFor(doc: MemberDoc): CompatibleWorkoutLog[] {
  return (doc.workoutLogs ?? []) as unknown as CompatibleWorkoutLog[];
}

/** Exported for the model context payload too, not just the safety gate. */
export function painFlagFor(doc: MemberDoc) {
  return [...workoutLogsFor(doc)]
    .reverse()
    .find(
      (log) => log.pain || log.painFlag || log.coachReviewRequired === true,
    );
}

/**
 * Safety signals are evaluated before any model call. The model must never be
 * asked to improvise around pain or a member-reported body signal.
 */
export function deterministicSafetyRecommendation(
  doc: MemberDoc,
): AiRecommendation | null {
  const now = new Date().toISOString();
  const pain = painFlagFor(doc);
  if (pain) {
    return {
      id: `recommendation-${randomUUID()}`,
      createdAt: now,
      kind: "coach_review",
      actionId: pain.actionId ?? pain.workoutId,
      evidence: ["A recent movement was logged with pain"],
      rationale:
        "Pain needs human review. Bharosa has not substituted or prescribed another exercise.",
      confidence: 1,
      safety: "coach_review",
      status: "needs_coach_review",
      source: "deterministic",
    };
  }

  // Acute and time-boxed on purpose: the last seven days of check-ins, not
  // "has she ever". A quiet week should let this clear on its own.
  const bodySignal = (doc.pulses ?? []).some(
    (pulse) => pulse.dayOffset >= -7 && (pulse.symptoms?.length ?? 0) > 0,
  );
  if (bodySignal) {
    return {
      id: `recommendation-${randomUUID()}`,
      createdAt: now,
      kind: "coach_review",
      evidence: ["A recent check-in includes a member-reported body signal"],
      rationale:
        "A coach should review this check-in. Bharosa has not inferred a cause or changed the plan in response.",
      confidence: 1,
      safety: "coach_review",
      status: "needs_coach_review",
      source: "deterministic",
    };
  }

  return null;
}
